---
image: Visual Studio 2019

branches:
  only:
    - master

skip_branch_with_pr: true

clone_depth: 1

cache:
  - vendor/bundle
  - ports/archives

install:
  - SET PATH=C:\ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --conservative
  - bundler --version
  - bundle config --local path vendor/bundle
  - bundle install

build: off

test_script:
  - bundle exec rake -rdevkit compile test

environment:
  matrix:
    - ruby_version: "31"
    - ruby_version: "30"
    - ruby_version: "27"
    - ruby_version: "26"
    - ruby_version: "25"
